/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    JuceCheckbox: typeof import('./components/JuceCheckbox.vue')['default']
    JuceComboBox: typeof import('./components/JuceComboBox.vue')['default']
    JuceSlider: typeof import('./components/JuceSlider.vue')['default']
    Knob: typeof import('./components/Knob.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    Slider: typeof import('./components/Slider.vue')['default']
  }
}
